const models = {
   users: {
      lid: null,
      afk: -1,
      afkReason: '',
      afkObj: {},
      bio: '-',
      banned: false,
      ban_temporary: 0,
      ban_times: 0,
      farming: {},
      fishing: {},
      hunting: {},
      crafting: {},
      point: 0,
      guard: 0,
      aset: 0,
      premium: false,
      lastclaim: 0,
      laststeal: 0,
      spinCount: 0,
      dailyReset: 0,
      transfer_history: [],
      saving_history: [],
      saving: 0,
      expired: 0,
      lastseen: 0,
      hit: 0,
      warning: 0,
      attempt: 0,
      code: '',
      codeExpire: 0,
      email: '',
      verified: false,
      taken: false,
      partner: '',
      authentication: false
   },
   groups: {
      activity: 0,
      antidelete: false,
      antilink: false,
      antivirtex: false,
      antitagsw: true,
      filter: false,
      left: false,
      localonly: false,
      mute: false,
      viewonce: false,
      autosticker: false,
      member: {},
      text_left: '',
      text_welcome: '',
      welcome: true,
      expired: 0,
      stay: false
   },
   chats: {
      chat: 0,
      lastchat: 0,
      lastseen: 0
   },
   setting: {
      autobackup: true,
      autodownload: true,
      antispam: true,
      debug: false,
      error: [],
      rset : [],
      hidden: [],
      pluginDisable: [],
      receiver: [],
      groupmode: false,
      sk_pack: 'Group Bot :',
      sk_author: 's.id/CylaAi',
      self: false,
      noprefix: true,
      multiprefix: true,
      prefix: ['.', '#', '!', '/'],
      toxic: ["ajg", "ajig", "anjas", "anjg", "anjim", "anjing", "anjrot", "anying", "asw", "autis", "babi", "bacod", "bacot", "bagong", "bajingan", "bangsad", "bangsat", "bastard", "bego", "bgsd", "biadab", "biadap", "bitch", "bngst", "bodoh", "bokep", "cocote", "coli", "colmek", "comli", "dajjal", "dancok", "dongo", "fuck", "gelay", "goblog", "goblok", "guoblog", "guoblok", "hairul", "henceut", "idiot", "itil", "jamet", "jancok", "jembut", "jingan", "kafir", "kanjut", "kanyut", "keparat", "kntl", "kontol", "lana", "loli", "lont", "lonte", "mancing", "meki", "memek", "ngentod", "ngentot", "ngewe", "ngocok", "ngtd", "njeng", "njing", "njinx", "oppai", "pantek", "pantek", "peler", "pepek", "pilat", "pler", "pornhub", "pucek", "puki", "pukimak", "redhub", "sange", "setan", "silit", "telaso", "tempek", "tete", "titit", "toket", "tolol", "tomlol", "tytyd", "xnxx"],
      online: true,
      onlyprefix: '+',
      owners: ['0'],
      lastReset: new Date * 1,
      msg: 'Hi +tag 🪸\nI am an automated system *Viola - Assistant* that can help to do something, search and get data / information only through WhatsApp.\n\n◦ *Version* : v+module\n◦ *Database* : +db\n◦ *Group* : Cooming Soon\n\nIf you find an error or want to upgrade premium plan contact the owner.',
      style: 4,
      cover: 'https://qu.ax/zAEvB.jpg',
      link: 'https://instagram.com/iamkizakixd'
   }
}

module.exports = { models }
